### ISSUE TITLE
How to automate deployment in github actions?

### ISSUE THREAD

**Issue by sunmingtao** [sunmingtao/devBoard#25]
**set up github secrete**

check current secrets
```gh secret list```

Add a secret
```gh secret set AWS_ACCESS_KEY_ID```

To manually add a secret

1. Go to GitHub repository: https://github.com/sunmingtao/devBoard
2. Click Settings → Secrets and variables → Actions
3. Click New repository secret

github workflow -- deploy-frontend.yml

```
name: Deploy Frontend to AWS

     on:
       push:
         branches:
           - main
         paths:
           - 'devboard-frontend/**'
           - '.github/workflows/deploy-frontend.yml'

     jobs:
       deploy:
         runs-on: ubuntu-latest

         steps:
         - name: Checkout code
           uses: actions/checkout@v3

         - name: Setup Node.js
           uses: actions/setup-node@v3
           with:
             node-version: '18'

         - name: Install dependencies
           working-directory: ./devboard-frontend
           run: npm ci

         - name: Build frontend
           working-directory: ./devboard-frontend
           run: npm run build

         - name: Configure AWS credentials
           uses: aws-actions/configure-aws-credentials@v2
           with:
             aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
             aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
             aws-region: us-east-1

         - name: Deploy to S3
           working-directory: ./devboard-frontend
           run: |
             aws s3 sync dist/ s3://devboard-frontend-627073650332 --delete

         - name: Invalidate CloudFront
           run: |
             aws cloudfront create-invalidation \
               --distribution-id E13IQLG4XH9EXL \
               --paths "/*"
```

github workflow -- deploy-backend.yml 
```
name: Deploy Backend to AWS

on:
  push:
    branches:
      - main
    paths:
      - 'devboard-backend/**'
      - '.github/workflows/deploy-backend.yml'

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: devboard-backend
  ECS_SERVICE: devboard-backend-alb
  ECS_CLUSTER: devboard-cluster
  ECS_TASK_DEFINITION: devboard-task-definition-rds.json

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
    
    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    
    - name: Build with Maven
      working-directory: ./devboard-backend
      run: mvn clean package -DskipTests
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
    
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    
    - name: Build, tag, and push image to Amazon ECR
      working-directory: ./devboard-backend
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker buildx create --use
        docker buildx build --platform linux/amd64 -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -t $ECR_REGISTRY/$ECR_REPOSITORY:latest --push .
    
    - name: Update ECS service
      run: |
        aws ecs update-service \
          --cluster ${{ env.ECS_CLUSTER }} \
          --service ${{ env.ECS_SERVICE }} \
          --force-new-deployment \
          --region ${{ env.AWS_REGION }}
    
    - name: Wait for service stability
      run: |
        aws ecs wait services-stable \
          --cluster ${{ env.ECS_CLUSTER }} \
          --services ${{ env.ECS_SERVICE }} \
          --region ${{ env.AWS_REGION }}
```

check whether workflow is correctly pushed

```
gh run list --workflow=deploy-frontend.yml --limit=5
gh run view 15791539823
```
